services:
  - type: web
    name: conversor-audio
    runtime: python
    buildCommand: ""
    startCommand: gunicorn conversor_texto_a_audio:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
