services:
  - type: web
    name: conversor-doc-audio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn conversor_texto_a_audio:aplicacion
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
